### ISSUE TITLE
Connexion LDAP (M2.6)

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#143]
cf. http://geonetwork-opensource.org/manuals/trunk/eng/users/admin/authentication/index.html#ldap

**Comment by fxprunayre** [comment]
- Vérifier que l'environnement de test peut accèder au LDAP
- Fournir la configuration pour le LDAP cf. https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/config-security/config-security.properties#L9 et https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/config-security/config-security-overrides.properties#L1)
- Tester avec metawal-4.X déployé en test SPW

Activer les logs DEBUG sur org.springframework.security et org.springframework.security.ldap
https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/classes/log4j.xml#L149

**Comment by davinciagf** [comment]
Test LDAP

```
ldapsearch -h 157.164.171.74 -p 651 -D "cn=tech_metawal,ou=tech_users,dc=external,dc=ovd" -w -b "dc=ovd" -s sub "objectclass=*"
```

```
2015-08-27 11:32:43,005 DEBUG [org.springframework.security.web.context.HttpSessionSecurityContextRepository] - HttpSession returned null object for SPRING_SECURITY_CONTEXT
2015-08-27 11:32:43,005 DEBUG [org.springframework.security.web.context.HttpSessionSecurityContextRepository] - No SecurityContext was available from the HttpSession: org.apache.catalina.session.StandardSessionFacade@eda9fb. A new one will be created.
2015-08-27 11:32:43,005 DEBUG [org.springframework.security.web.FilterChainProxy] - /j_spring_security_check at position 2 of 11 in additional filter chain; firing Filter: 'LogoutFilter'
2015-08-27 11:32:43,005 DEBUG [org.springframework.security.web.FilterChainProxy] - /j_spring_security_check at position 3 of 11 in additional filter chain; firing Filter: 'MultiNodeAuthenticationFilter'
2015-08-27 11:32:43,005 DEBUG [org.springframework.security.web.FilterChainProxy] - /j_spring_security_check at position 4 of 11 in additional filter chain; firing Filter: 'PassthroughFilter'
2015-08-27 11:32:43,005 DEBUG [org.springframework.security.web.FilterChainProxy] - /j_spring_security_check at position 5 of 11 in additional filter chain; firing Filter: 'BasicAuthenticationFilter'
2015-08-27 11:32:43,005 DEBUG [org.springframework.security.web.FilterChainProxy] - /j_spring_security_check at position 6 of 11 in additional filter chain; firing Filter: 'UsernamePasswordAuthenticationFilter'
2015-08-27 11:32:43,005 DEBUG [org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter] - Request is to process authentication
2015-08-27 11:32:43,006 DEBUG [org.springframework.security.authentication.ProviderManager] - Authentication attempt using org.fao.geonet.kernel.security.GeonetworkAuthenticationProvider
2015-08-27 11:32:43,009 WARN  [org.springframework.context.support.ResourceBundleMessageSource] - ResourceBundle [messages] not found for MessageSource: Can't find bundle for base name messages, locale fr_FR
2015-08-27 11:32:43,085 WARN  [org.springframework.context.support.ResourceBundleMessageSource] - ResourceBundle [messages] not found for MessageSource: Can't find bundle for base name messages, locale fr_FR
2015-08-27 11:32:43,085 DEBUG [org.springframework.security.authentication.ProviderManager] - Authentication attempt using org.springframework.security.ldap.authentication.LdapAuthenticationProvider
2015-08-27 11:32:43,085 WARN  [org.springframework.context.support.ResourceBundleMessageSource] - ResourceBundle [messages] not found for MessageSource: Can't find bundle for base name messages, locale fr_FR
2015-08-27 11:32:43,085 DEBUG [org.springframework.security.ldap.authentication.LdapAuthenticationProvider] - Processing authentication request for user: arnaud
2015-08-27 11:32:43,087 DEBUG [org.springframework.security.ldap.authentication.BindAuthenticator] - Attempting to bind as uid=arnaud,ou=people,dc=external,dc=ovd
2015-08-27 11:32:43,087 DEBUG [org.springframework.security.ldap.DefaultSpringSecurityContextSource] - Removing pooling flag for user uid=arnaud,ou=people,dc=external,dc=ovd
2015-08-27 11:35:52,246 ERROR [org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter] - An internal error occurred while trying to authenticate the user.
org.springframework.security.authentication.InternalAuthenticationServiceException: 157.164.171.74:6051; nested exception is javax.naming.CommunicationException: 157.164.171.74:6051 [Root exception is java.net.ConnectException: Connection timed out]
        at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:191)
        at org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:61)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156)
        at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:195)

```

**Comment by vbombaerts** [comment]
Pas réussi à m'identifier dans l'application.
En outre, en tant qu'admin, il n'y a plus aucun utilisateur dans l'application.

**Comment by vbombaerts** [comment]
OK pour connexion LDAP. KO pour utilisateurs hors LDAP cf #302
