### ISSUE TITLE
Moissonnage de l'IGN

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#643]
J'essaie de moissonner dans l'env de test une fiche de l'IGN sur le point [http://csw.geo.be/eng/csw](http://csw.geo.be/eng/csw?request=GetCapabilities&service=CSW&version=2.0.2)
J'ai essayé 
- ISO 19115-3 - pas de résultat (point Geo.be en 19115-3)
- ISO 19139 (avec et sans transformation) - 1 fiche moissonnée mais qui n'apparait pas dans Metawal (points Geo.be en 19139, Geo.be 19139 vers ISO 19115-3 et Geo.be 19139 vers 19115-3/2018)

**Comment by fxprunayre** [comment]
J'arrive bien à moissonner le CSW

![image](https://user-images.githubusercontent.com/1701393/131843787-649a3ff2-ae42-43fb-a9cb-c459d4cf9a91.png)

2 fiches suspectes.

Faut demander du ISO19139 car a priori il ne connait pas 115-3. 

Donc je vois pas trop le pb.

**Comment by fxprunayre** [comment]
![image](https://user-images.githubusercontent.com/1701393/131848745-38b5b3cd-77d3-4d8d-9569-7df78fd1fae7.png)

avec le filtre sur le titre TITLE LIKE %CartoWeb.be%

**Comment by vbombaerts** [comment]
C'est ok maintenant.
Par contre, elle n'apparait pas sur le GP. Je vais investiguer.
http://geoportail.test.wallonie.be/catalogue-donnees-et-services?search-changed=false+++&search-tri=relevance&search-tab=2&search-perPage=&search-text=cartoweb&search-diffusion-service-type=&search-not-obsolete=true&search-not-inspire=true&search-mapDate=&search-sheetDate=#results-area

**Comment by vbombaerts** [comment]
Ne fonctionne pas en valid.

Erreur : `Bad server response: 'authenticationrequired -- URI: http://csw.geo.be/eng/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2 -- Response Code: 407' `

Le serveur est accessible depuis un navigateur. 

Log complet de l'erreur

```
2021-09-28T13:04:08,567+0200 INFO  [IGN] - Starting harvesting of IGN
2021-09-28T13:04:08,597+0200 INFO  [IGN] - Started harvesting from node : IGN (CswHarvester)
2021-09-28T13:04:08,639+0200 WARN  [IGN] - Raised exception while harvesting from : IGN (CswHarvester)
2021-09-28T13:04:08,639+0200 WARN  [IGN] -  (C) Class   : BadServerResponseEx
2021-09-28T13:04:08,639+0200 WARN  [IGN] -  (C) Message : Bad server response: 'authenticationrequired -- URI: http://csw.geo.be/eng/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2 -- Response Code: 407'
2021-09-28T13:04:08,639+0200 ERROR [IGN] - Bad server response: 'authenticationrequired -- URI: http://csw.geo.be/eng/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2 -- Response Code: 407'
BadServerResponseEx : Bad server response: 'authenticationrequired -- URI: http://csw.geo.be/eng/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2 -- Response Code: 407'
	at org.fao.geonet.utils.XmlRequest.executeAndReadResponse(XmlRequest.java:124)
	at org.fao.geonet.utils.XmlRequest.execute(XmlRequest.java:85)
	at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.retrieveCapabilities(Harvester.java:162)
	at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.harvest(Harvester.java:104)
	at org.fao.geonet.kernel.harvest.harvester.csw.CswHarvester.doHarvest(CswHarvester.java:95)
	at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester$HarvestWithIndexProcessor.process(AbstractHarvester.java:605)
	at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester.harvest(AbstractHarvester.java:676)
	at org.fao.geonet.kernel.harvest.harvester.HarvesterJob.execute(HarvesterJob.java:69)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by vbombaerts** [comment]
Possible de se connecter au service en prod, mais pas possible d'activer un filtre.
@davinciagf tu peux vérifier que c'est la bonne version qui a été montée en prod STP ?

**Comment by davinciagf** [comment]
L'encodage de l'url devrait permettre d'activer les filtres suite à une requête de type getcapabilities sur l'url de moissonnage. Cette requête ne passe pas en prod actuellement. Je regarde avec Didier si lié au proxy

**Comment by vbombaerts** [comment]
Je le passe sur la 4.0.7 "Version où on résout tous les problèmes côté DTIC" ;-p

**Comment by davinciagf** [comment]
La connexion vers des catalogues externes semble ok en prod. Le getCapabilities passe et on peut donc définir des filtres. 

![image](https://user-images.githubusercontent.com/576292/137293966-5ced24f3-5ef7-4104-87eb-1fc22117b142.png)

Pas opérationnel pour la valid. Demande à Didier en cours

**Comment by davinciagf** [comment]
La valid n'a pas l'autorisation d'utilisation du proxy.

**Comment by vbombaerts** [comment]
C'était un peu laborieux mais finalement j'y suis arrivé.
(en tapant l'adresse du CSW - pas de connexion ; en copiant/collant l'adresse du CSW - connexion OK)

![image](https://user-images.githubusercontent.com/6093597/137331191-b72e06e7-80ce-4236-80b7-f1bb6713f68b.png)

**Comment by davinciagf** [comment]
Autorisation modifiée en valid.
