### ISSUE TITLE
Moissonnage de l'IGN ne fonctionne pas en valid.

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#664]
Erreur : `Bad server response: 'authenticationrequired -- URI: http://csw.geo.be/eng/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2 -- Response Code: 407' `

Le serveur est accessible depuis un navigateur. 

Log complet de l'erreur

```
2021-09-28T13:04:08,567+0200 INFO  [IGN] - Starting harvesting of IGN
2021-09-28T13:04:08,597+0200 INFO  [IGN] - Started harvesting from node : IGN (CswHarvester)
2021-09-28T13:04:08,639+0200 WARN  [IGN] - Raised exception while harvesting from : IGN (CswHarvester)
2021-09-28T13:04:08,639+0200 WARN  [IGN] -  (C) Class   : BadServerResponseEx
2021-09-28T13:04:08,639+0200 WARN  [IGN] -  (C) Message : Bad server response: 'authenticationrequired -- URI: http://csw.geo.be/eng/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2 -- Response Code: 407'
2021-09-28T13:04:08,639+0200 ERROR [IGN] - Bad server response: 'authenticationrequired -- URI: http://csw.geo.be/eng/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2 -- Response Code: 407'
BadServerResponseEx : Bad server response: 'authenticationrequired -- URI: http://csw.geo.be/eng/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2 -- Response Code: 407'
	at org.fao.geonet.utils.XmlRequest.executeAndReadResponse(XmlRequest.java:124)
	at org.fao.geonet.utils.XmlRequest.execute(XmlRequest.java:85)
	at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.retrieveCapabilities(Harvester.java:162)
	at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.harvest(Harvester.java:104)
	at org.fao.geonet.kernel.harvest.harvester.csw.CswHarvester.doHarvest(CswHarvester.java:95)
	at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester$HarvestWithIndexProcessor.process(AbstractHarvester.java:605)
	at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester.harvest(AbstractHarvester.java:676)
	at org.fao.geonet.kernel.harvest.harvester.HarvesterJob.execute(HarvesterJob.java:69)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

_Originally posted by @vbombaerts in https://github.com/SPW-DIG/metawal-core-geonetwork/issues/643#issuecomment-929086839_

**Comment by davinciagf** [comment]
Cela passe en prod et en test. Demandes faites à Didier pour la valid

**Comment by davinciagf** [comment]
La valid ne serait pas autorisé à utiliser le proxy... Demande de modif faite par Didier

**Comment by davinciagf** [comment]
Autorisation modifiée en valid.

**Comment by vbombaerts** [comment]
Toujours des problèmes pour configurer ce moissonneur de l'IGN très très capricieux. 
Il est accessible depuis la test, mais pas possible d'utiliser les filtres.
Peut-être parce qu'il n'est pas sécurisé ?

Aucun problème avec le CSW de la Flandre. 
Et j'ai réussi à configuré correctement l'IGN en prod.

C'est suffisant pour moi. Je ferme.
