### ISSUE TITLE
Moissonnage geo.be - ne moissonne pas toutes les fiches répondant aux critères

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#812]
On avait configuré en prod un moissonneur qui permet de récupérer les fiches TransStat relatives à la Wallonie sur le catalogue geo.be
Récemment, deux fiches ont été ajoutées côté geo.be. Elles contiennent toutes les deux les mots Wallonie et TransStat, qui sont les mots-clés définis dans le filtre du moissonneur. Pourtant ces deux nouvelles fiches ne remontent pas dans le moissonneur. Une idée de ce qui coince ?

**Comment by fxprunayre** [comment]
Tu peux nous donner un UUID pour retrouver ces nouvelles fiches ?

**Comment by vbombaerts** [comment]
Part de la surface cadastrée artificialisée en Wallonie
https://www.geo.be/catalog/details/1e7084c0-e8c3-11ec-a3e2-186571a04de2?l=fr

Part de la surface cadastrée non artificialisée en Wallonie
https://www.geo.be/catalog/details/8ac4f051-e8c0-11ec-b13b-186571a04de2?l=fr

**Comment by fxprunayre** [comment]
Sans la config batch editing, ca semble ok. Donc on doit avoir des erreurs par là...

**Comment by fxprunayre** [comment]
En effet dans le log

```

2023-03-15T09:41:46,582+0100 ERROR [TransStat_Wallonie_unilingue] -    Record failed: 1e7084c0-e8c3-11ec-a3e2-186571a04de2. Error is: java.lang.NullPointerException
2023-03-15T09:41:46,582+0100 ERROR [TransStat_Wallonie_unilingue] - java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at org.fao.geonet.kernel.EditLib.addElementOrFragmentFromXpath(EditLib.java:619)
	at org.fao.geonet.kernel.harvest.harvester.csw.Aligner.applyBatchEdits(Aligner.java:390)
```

**Comment by fxprunayre** [comment]
J'aurai pas bien le temps de creuser plus aujourd'hui, mais en désactivant l'option:
![image](https://user-images.githubusercontent.com/1701393/225303048-b47aebc8-2527-41af-a9a5-60e5c9b04202.png)
ca me semble ok.

Cette option est aussi utilisée par l'API de batch et donc en mode replace il tente de créer l'élément qui n'existe pas. J'aurai tendance à dire qu'en mode replace on ne devrait jamais tenter de créer quelquechose qui n'existe pas voire cette option ne devrait pas être utilisée dans l'API de batch. A vérifier.

Sur ces fiches on échoue sur
```
{
    "xpath": "/mdb:distributionInfo/*/mrd:transferOptions/*/mrd:onLine/cit:CI_OnlineResource[starts-with(cit:linkage/*/text(), 'https://walstat.iweps.be/fichiers/donnees') or starts-with(cit:linkage/*/text(), 'https://opendata.iweps.be/api/data')]/cit:function",
    "value": "<gn_replace><cit:CI_OnLineFunctionCode xmlns:cit=\"http://standards.iso.org/iso/19115/-3/cit/2.0\" codeList=\"http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode\" codeListValue=\"download\"/></gn_replace>"
  },
```

**Comment by vbombaerts** [comment]
En effet ça passe en désactivant l'option. A voir si on a des effets de bord.
